// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        int64
	AuthorID  int64
	Title     string
	Content   string
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID                 int64
	Email              string
	Username           string
	PasswordHash       string
	IsActive           bool
	TokenInvalidBefore pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
