// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (author_id, title, content)
VALUES ($1, $2, $3)
RETURNING id, author_id, title, content, updated_at, created_at
`

type CreatePostParams struct {
	AuthorID int64
	Title    string
	Content  string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.AuthorID, arg.Title, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Content,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAllPosts = `-- name: GetAllPosts :many
SELECT p.id, p.author_id, p.title, p.content, p.updated_at, p.created_at, u.username FROM posts p JOIN users u ON u.id = p.author_id
`

type GetAllPostsRow struct {
	ID        int64
	AuthorID  int64
	Title     string
	Content   string
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Username  string
}

func (q *Queries) GetAllPosts(ctx context.Context) ([]GetAllPostsRow, error) {
	rows, err := q.db.Query(ctx, getAllPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPostsRow
	for rows.Next() {
		var i GetAllPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Content,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
