// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, username, password_hash, is_active, token_invalid_before, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.TokenInvalidBefore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByEmail = `-- name: GetByEmail :one
SELECT
  u.id,
  u.email,
  u.username,
  u.password_hash,
  u.is_active,
  u.token_invalid_before,
  u.created_at,
  u.updated_at
FROM users u
WHERE u.email = $1 AND u.is_active = TRUE
`

// for testing purpose we are getting al info
func (q *Queries) GetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.TokenInvalidBefore,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
